### ISSUE TITLE
Launcher roadmap for Q1 2017

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#261]
I have been working for a list of features coming in Launcher in Q1. The below list does not include layouts/compositions, because these will be separate from Launcher as the first tasks.

- [ ] 1. Turn LayoutEditor into an app (https://github.com/Starcounter/RebelsLounge/issues/47, https://github.com/StarcounterPrefabs/Launcher/pull/259)
- [ ] 2. Turn LayoutProvider into an app (https://github.com/Starcounter/RebelsLounge/issues/47, https://github.com/StarcounterPrefabs/Launcher/pull/259) and discuss including it in Starcounter
- [ ] 3. Turn workspace into middleware (https://github.com/StarcounterPrefabs/Launcher/issues/260)
- [ ] 4. Discuss including this middleware in Starcounter
- [ ] 5. Make Launcher run itself in a workspace (https://github.com/StarcounterPrefabs/Launcher/issues/248)
- [ ] 6. URI Mapping improvements that allow dynamic changes (https://github.com/Starcounter/Starcounter/issues/2554)
- [ ] 7. URI Mapping improvements that allow multiple responses from a single app (https://github.com/Starcounter/Starcounter/issues/3118)
- [ ] 8. URI Mapping flexibility improvements (https://github.com/Starcounter/Starcounter/issues/2930)
- [ ] 9. Merge Launcher with Website app (https://github.com/StarcounterPrefabs/Website/issues/12)
- [ ] 10. Implement full page sign in (https://github.com/StarcounterPrefabs/Launcher/issues/240)
- [ ] 11. Implement Launcher menus (https://github.com/Starcounter/RebelsLounge/issues/53)
- [ ] 12. Present how part of Launcher (page title - string) can be configured, instead of hardcoded (https://github.com/StarcounterPrefabs/Launcher/issues/245)
- [ ] 13. Present how part of Launcher (favicon - file upload, or Base64 string) can be configured, instead of hardcoded (https://github.com/StarcounterPrefabs/Launcher/issues/252)
- [ ] 14. Present how part of Launcher (CSS color scheme - color picker) can be configured, instead of hardcoded (https://github.com/StarcounterPrefabs/Launcher/issues/252)

Points 1-2 are already started. Points 3-5 might involve @chrhol. Points 6-8 will involve @alemoi.

**Comment by warpech** [comment]
@tomalec, @miyconst, @chrhol, @alemoi, @mmnosek, @aloscha, @jwillmer, @malx122 comments welcome.

**Comment by miyconst** [comment]
Looks good and it would be impressive if we can get all of those done in Q1.

Why the points 6-8 are included into the Launcher issue? I think it is a restriction inside Starcounter itself, and @alemoi most likely won't be able to help here, probably @chrhol could.

**Comment by warpech** [comment]
> Why the points 6-8 are included into the Launcher issue? I think it is a restriction inside Starcounter itself, and @alemoi most likely won't be able to help here, probably @chrhol could.

I wanted to have 6-8 on the roadmap, because they are prerequisite to the points that follow. Right now Website app has internally its own internal mapping, which is not `UriMapping`. That should change.

**Comment by mmnosek** [comment]
Looks pretty good for me, but one more question - what about SWO specific requirements? I mean things like:
* separate colors for header, menu and font
* company logos shown in different places, managed at one configuration page
* storing whole theme configuration with different names, possible to reuse when needed

Also, I think that
> 14. Present how part of Launcher (CSS color scheme - color picker) can be configured, instead of hardcoded (#252)
Does not refer to #252

**Comment by warpech** [comment]
> Looks pretty good for me, but one more question - what about SWO specific requirements? I mean things like:
* separate colors for header, menu and font
* company logos shown in different places, managed at one configuration page
* storing whole theme configuration with different names, possible to reuse when needed

This will come as the result of points 9-14. At that point it should be possible to do SWO specific requirements **both** as on-the-fly config of Launcher or as a fork of Launcher. The decision will be a matter of convenience.

Adapting the new SWO theme on top of that might take few weeks on its own, which is a good catch by you.

> Also, I think that
> > 14. Present how part of Launcher (CSS color scheme - color picker) can be configured, instead of hardcoded (#252)
> Does not refer to #252 

Good catch, I have removed the link.

**Comment by jwillmer** [comment]
Well I thought the goal is that SWO (and other company's) does not need to fork the Launcher but can instead customize it or extend it with apps. If we need to create a fork we can skip it all together and we use the current one - no need to wait for 1-2 generalizations.

**Comment by warpech** [comment]
> If we need to create a fork we can skip it all together and we use the current one - no need to wait for 1-2 generalizations.

It is **might**, not **need**.

Doing a fork right now is a messy workaround for the lack of flexibility. After the changes listed in OP, a fork would be "thin", because everything might come dynamically from database **or** static code - doing a fork will be a matter of choice, not necessity.

To illustrate: our Launcher comes with a set of config options (points 12-14). There is a simple yet dynamic template and 3 configuration controls for it. But I bet you will have a more complex template with its own static files and configuration controls. Then if you need some fancy controls for your theme, you will need to have either "SWOConfigurator" app that will update the Launcher templates or a Launcher fork that will have them built-in.

**Comment by jwillmer** [comment]
O.K., I understand. In that case I am happy 👍

**Comment by warpech** [comment]
To wrap up, after the changes it should be possible to:

- define arbitrary number of UI regions in Launcher
- map arbitrary content to these regions, coming both from app code handlers and from database
- in the database content, use variables that allow run-time customisability

**Comment by alemoi** [comment]
I would do URI mapping changes with pleasure! As always a bit stucked on other stuff, but soon will have no choice and will have to fix this mapping :)

**Comment by warpech** [comment]
Update. Points https://github.com/Starcounter/level1/issues/2554, https://github.com/Starcounter/level1/issues/3118, https://github.com/Starcounter/level1/issues/2930, https://github.com/Starcounter/level1/issues/4061, https://github.com/StarcounterApps/Website/issues/12 are now done.

Will do an update about other points soon.
